# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datawarehouse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'datawarehouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61tawarehouse.proto\"\xd5\x01\n\tWarehouse\x12\x13\n\x0bwarehouseID\x18\x01 \x01(\t\x12\x15\n\rwarehouseName\x18\x02 \x01(\t\x12\x18\n\x10warehouseAddress\x18\x03 \x01(\t\x12\x1b\n\x13warehousePostalCode\x18\x04 \x01(\t\x12\x15\n\rwarehouseCity\x18\x05 \x01(\t\x12\x18\n\x10warehouseCountry\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\x12!\n\x0bproductdata\x18\x08 \x03(\x0b\x32\x0c.ProductData\"|\n\x0bProductData\x12\x11\n\tproductID\x18\x01 \x01(\t\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\x17\n\x0fproductCategory\x18\x03 \x01(\t\x12\x17\n\x0fproductQuantity\x18\x04 \x01(\x05\x12\x13\n\x0bproductUnit\x18\x05 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\x14\x44\x61taWarehouseService\x12!\n\rsendWarehouse\x12\n.Warehouse\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datawarehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WAREHOUSE']._serialized_start=24
  _globals['_WAREHOUSE']._serialized_end=237
  _globals['_PRODUCTDATA']._serialized_start=239
  _globals['_PRODUCTDATA']._serialized_end=363
  _globals['_ACK']._serialized_start=365
  _globals['_ACK']._serialized_end=387
  _globals['_DATAWAREHOUSESERVICE']._serialized_start=389
  _globals['_DATAWAREHOUSESERVICE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
